spring.application.name: rsaga.common

spring:
  datasource:
    url: jdbc:mysql://192.168.35.179:3306/reservation-saga
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: master
    password: master

  main:
    web-application-type: none